version: "3.8"

services:
  auth-service:
    container_name: auth
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m app.microservices.auth.main
    expose:
      - "50051"
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    volumes:
      - ./migrations/versions:/migrations/versions

  auth-db:
    image: postgres:16
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

