version: "3.8"

services:
  auth-service:
    build: .
    depends_on:
      - auth-db
    ports:
      - "8000:8000"  
      - "50053:50053"
    command: python -m app.microservices.auth.main

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - auth-db-data:/var/lib/postgresql/data


volumes:
  auth-db-data:
